import { Schema, model } from "mongoose";

const tbl_fichero_colombia = Schema(
  {
    nro_medico: String,
    Cdg_ciudad: String,
    Cdg_medico: String,
    Matricula1: String,
    Matricula2: String,
    Matricula3: String,
    Apeynom: String,
    Apellido_Paterno: String,
    Apellido_Materno: String,
    Nombres: String,
    Sexo: String,
    Direccion1:String,
    Calle1: String,
    Altura1: String,
    Barrio_Municipio1: String,
    Localidad_Colonia1: String,
    Cdg_postal1: String,
    Cdg_Zona1: String,
    Espec:String,
    cdg_espec1: String,
    cdg_espec2: String,
    FAlta: String,
    FModResto: String,
    FModDom: String,
    UsuModDom: String,
    UsuRevisionDom:  String ,
    Id_Unico: String,
    Activo:String,
    MUnico_Activo: String,
    EstadoGralMedico:String,
    Seguimiento: String,
    cdg_instit1: String,
    UsuConfAlta: String,
    Fecha_Conf_Alta: String,
    cdg_usu_alta: String,
    Fecha_Alta: String,
    Cdg_Usu_Inact_act: String,
    Usu_Inact_act:  String, 
    OrigDom: String,
    MetObtDom: String,
    DomModif: String,
    DomModif2: String,
    cdg_instit2: String,
    PxTamMKT: String,
    PxTamTGT: String,
    Publicado: String,
    PxTGT_202008: String,
    PxTGT_202009: String,
    PxTGT_202010: String,
    PxTGT_202011: String,
    PxTGT_202012: String,
    PxTGT_202101: String,
    PxTGT_202102: String,
    PxTGT_202103: String,
    PxTGT_202104: String,
    PxTGT_202105: String,
    PxTGT_202106: String,
    PxTGT_202107: String,
    Cdg_Utc: String,
    Desc_Utc: String,
    cdg_soft: String,
    MedicoPublicar: String,
    Cod_instit_nac: String,
    Cod_instit_nac2: String,
  },
  {
    timestamps: true,
  }
);

export default model("tbl_fichero_colombia", tbl_fichero_colombia);
